# Generated by Django 4.2.4 on 2023-09-25 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_product_last_modified_date_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='versions',
            field=models.ManyToManyField(blank=True, related_name='products', to='catalog.version', verbose_name='Версии продукта'),
        ),
    ]
